// Build-time app/version/git metadata for the Dynatrace Footprint App.
//
// This project builds with the Dynatrace App Toolkit (`dt-app`, esbuild-based),
// not Vite — so instead of a Vite `define` block we generate a small TypeScript
// module that the UI imports. `getBuildInfo()` is exported so it can also be
// consumed by a bundler config or other tooling if desired.
//
// Running this file directly (see the npm `prebuild`/`predeploy`/`prestart`
// hooks) writes `ui/app/generated/build-info.ts`.

import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

function git(command, fallback) {
  try {
    return execSync(command, {
      cwd: ROOT,
      stdio: ["ignore", "pipe", "ignore"],
    })
      .toString()
      .trim();
  } catch {
    return fallback;
  }
}

function readJson(relativePath) {
  try {
    return JSON.parse(readFileSync(resolve(ROOT, relativePath), "utf8"));
  } catch {
    return null;
  }
}

/**
 * @returns {{ version: string, commitHash: string, commitDate: string }}
 */
export function getBuildInfo() {
  // Version source of truth: the deployed app manifest (app.config.json).
  // Fall back to package.json, then a safe default, so builds never fail here.
  const appConfig = readJson("app.config.json") ?? readJson("app.config.example.json");
  const pkg = readJson("package.json");
  const version =
    appConfig?.app?.version || pkg?.version || "0.0.0";

  const commitHash = git("git rev-parse --short HEAD", "unknown");
  const commitDate = git("git log -1 --format=%cI", "");

  return { version, commitHash, commitDate };
}

function writeGeneratedModule(info) {
  const outDir = resolve(ROOT, "ui/app/generated");
  mkdirSync(outDir, { recursive: true });
  const contents =
    "// AUTO-GENERATED by scripts/build-info.mjs — do not edit.\n" +
    "// Regenerated on every build via the npm prebuild/predeploy/prestart hooks.\n" +
    `export const APP_VERSION = ${JSON.stringify(info.version)};\n` +
    `export const COMMIT_HASH = ${JSON.stringify(info.commitHash)};\n` +
    `export const COMMIT_DATE = ${JSON.stringify(info.commitDate)};\n`;
  writeFileSync(resolve(outDir, "build-info.ts"), contents);
}

// Execute the generator when run as a script (not when imported).
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const info = getBuildInfo();
  writeGeneratedModule(info);
  console.log(
    `[build-info] v${info.version} · ${info.commitHash} · ${info.commitDate || "no-date"}`
  );
}
